export {default as Dashboard} from './Dashboard'
export {default as Allvehicle } from './AllVehicle'
export {default as AllClaims } from './AllClaims'
export {default as MyVehicle } from './MyVehicle'
export {default as MyClaim } from './MyClaim'
export {default as Policies } from './Policies'
export {default as InsurancePolicyRegister} from './InsurancePolicy'
export {default as VehicleRegisteration} from '../components/VehicleRegisteration'
export {default as  ClaimSubmission} from '../components/ClaimSubmission'
export {default as  ClaimDetails} from '../components/ClaimDetails'
export {default as  PolicyDetails} from '../components/PolicyDetails'